kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress
  namespace: multilayer-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'wordpress:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:8.0-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/verissimomoraes/lab-gitops-app.git'
      ref: wp-codigo
    contextDir: /
  runPolicy: Serial