apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitops-app
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      seLinuxOptions:
        level: 's0:c27,c4'
      supplementalGroups:
        - 1000710001
      fsGroup: 0
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/gitops-app/wordpress:11
        name: wordpress
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: wordpress-secret
          - configMapRef:
              name: wp-configmap
        resources:
          limits:
            cpu: 2
            memory: 2048Mi
          requests:
            cpu: 1
            memory: 1024Mi
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
