kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ig-wordpress
  namespace: gitops-app
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
  - host: wordpress-dev.apps.bbassetnonprod.brazilsouth.aroapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-svc-clusterip
            port:
              number: 80
