apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ing
  namespace: gitops-app
spec:
  ingressClassName: nginx
  rules:
  - host: wordpress.35.171.150.239.sslip.io
    http:
      paths:
      - backend:
          service:
            name: wordpress-svc-clusterip
            port:
              number: 80
        path: /
        pathType: Prefix
