apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitops-app
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn  	
  resources:
    requests:
      storage: 1Gi