apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitops-app
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: longhorn
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
