apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: multilayer-app
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: longhorn
  #storageClassName: azurefile-csi
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
