apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  namespace: gitops-app
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
