apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress-svc-clusterip
  namespace: gitops-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wordpress
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
