apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: st-mysql
  namespace: gitops-app
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: database
          image: mysql:5.6
          args:
            - '--ignore-db-dir=lost+found'
          envFrom:
            - secretRef:
                name: my-secret
            - configMapRef:
                name: my-configmap    
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      namespace: gitops-app
    spec:
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
